### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Class com.ssomar.executableitems.executableitems.manager.ExecutableItemsManager does not implement the requested interface com.ssomar.score.api.executableitems.config.ExecutableItemsManagerInterface

### ISSUE THREAD

**Issue by MeexReay** [Ssomar-Developement/SCore#28]
Full error:

```
[03:15:12 ERROR]: Could not pass event PlayerCommandPreprocessEvent to DeluxeMenus v1.14.1-DEV-null
java.lang.IncompatibleClassChangeError: Class com.ssomar.executableitems.executableitems.manager.ExecutableItemsManager does not implement the requested interface com.ssomar.score.api.executableitems.config.ExecutableItemsManagerInterface
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor3626.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-260]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-260]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-260]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2183) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$19(ServerGamePacketListenerImpl.java:2167) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-260]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-260]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-260]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-260]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-260]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-260]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-260]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-260]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

My code:

```java
ExecutableItemsManagerInterface eim = ExecutableItemsAPI.getExecutableItemsManager();
```

plugin.yml

```yml
softdepend: [ PlaceholderAPI, Vault, HeadDatabase, ItemsAdder, Oraxen, ExecutableItems, ExecutableBlocks, SCore ]
depend:
  - ExecutableItems
```

build.gradle.kts

```kts
repositories {
    mavenCentral()
    maven("https://jitpack.io")
    flatDir {
        dirs("src/main/resources/")
    }
}

dependencies {
    compileOnly("com.github.Ssomar-Developement:SCore:4.24.3.10")
}
```

I am using SCore 4.24.3.10 and ExecutableItems Premium 6.24.3.10

**Comment by ssomar1607** [comment]
Hello, you can contact me if you have a problem, it's caused because you probably merge SCore into your plugin jar.
